version: '3'
services:
  django:
    container_name: django
    image: yapie/django
    working_dir: /code 
    command: bash -c 'gunicorn mysite.wsgi:application -b 0.0.0.0:8000'
    networks: 
      django_net:
          aliases:
            - django
  
  nginx:
    container_name: nginx
    image: yapie/nginx
    working_dir: /code 
    ports:
     - 80:80
    networks: 
     - django_net

networks:
  django_net:
    driver: bridge
